Migrate category page to bootstrap
VirtoCommerce/vc-demo-theme-b2b pull request #186
Opened 2021-03-04 10:14 UTC by asvishnyakov

Description: 
Migrate category page to bootstrap

--

QA-test: 

Demo-test: 

Download artifact URL:

2021-03-10 07:38 UTC, ilyawzrd commented on assets/scss/bootstrap-migration/override/_input-group.scss
> +.input-group > .form-control:not(textarea),
Remove this code

2021-03-10 07:40 UTC, ilyawzrd requested changes

2021-03-10 07:40 UTC, ilyawzrd commented on assets/scss/bootstrap-migration/override/_input-group.scss
> +.input-group > .form-control:not(textarea),
Remove this code

2021-03-15 14:15 UTC, trueboroda approved these changes

2021-03-17 16:55 UTC, merged