VP-5105: Add block for configuring order in product page
VirtoCommerce/vc-demo-theme-b2b pull request #72
Opened 2020-09-28 12:12 UTC by ilyawzrd

2020-09-28 15:07 UTC, pushnitsa commented
Too much free space :)
![image](https://user-images.githubusercontent.com/15198683/94449744-bb1a5580-01ac-11eb-90af-27fec12abcd6.png)

1. Image is missed
2. Markup is broken
![image](https://user-images.githubusercontent.com/15198683/94449967-f6b51f80-01ac-11eb-9374-d6b5c0254f8c.png)

2020-09-28 15:34 UTC, ilyawzrd commented
Empty space is removed if tech specs for product are small
![image](https://user-images.githubusercontent.com/22875828/94453289-ca030700-01b0-11eb-886a-d48c25d053b2.png)

2020-09-28 18:57 UTC, ilyawzrd commented
Fix card layout for configurable product
![Screenshot_8](https://user-images.githubusercontent.com/22875828/94473864-12302280-01cd-11eb-8049-9a599a9616c6.png)

2020-09-29 08:47 UTC, pushnitsa requested changes

2020-09-29 08:47 UTC, pushnitsa commented on assets/js/product.js
> +                const foundIndex = $scope.productParts.findIndex(x => x.name == productPart.name);
Please use strict comparing

2020-09-29 08:47 UTC, pushnitsa commented on assets/js/product.js
> +            const item = configPart.items.find(x => x.id == configPart.selectedItemId);
Use strict comparing

2020-09-29 08:51 UTC, pushnitsa approved these changes

2020-09-29 13:12 UTC, merged