VP-5525 Add 'Credit Card' payment method for a 'Purchasing Agent' role
VirtoCommerce/vc-demo-theme-b2b pull request #95
Opened 2020-10-14 13:28 UTC by trueboroda

For DoD see  
https://virtocommerce.atlassian.net/browse/VP-4632

2020-10-14 14:03 UTC, pushnitsa requested changes

2020-10-14 14:03 UTC, pushnitsa commented on assets/js/checkout/dialogs/checkout-select-payment-method.js
> +        if(paymentMethod.logoUrl) {
Logo url comes from backend always should be ignored

2020-10-14 14:03 UTC, pushnitsa commented on assets/js/checkout/dialogs/checkout-select-payment-method.js
> +    $scope.getPaymentIconUrl = function(paymentMethod) {
checkout.js contains the same code, fix there too

2020-10-15 09:21 UTC, trueboroda commented
Last visual changes 
![image](https://user-images.githubusercontent.com/13153256/96103862-db525000-0ee0-11eb-87f9-e2d71d6319c7.png)
![image](https://user-images.githubusercontent.com/13153256/96103919-e9a06c00-0ee0-11eb-845b-be1b9d349cbc.png)

2020-10-15 09:35 UTC, pushnitsa approved these changes

2020-10-15 09:36 UTC, merged